name: UtkScriptLoaderPlugin
version: pre3.0.0-1.16.4-rev6
author: utk003
main: io.github.utk003.spigot_scripting.plugin.PluginMain
api-version: 1.16
description: A custom script-loading program for easily configurable server modifications
commands:
  usl:
    description: |
      Command for the Utk Script Loader Plugin
      Check out "/usl help" for more info
    aliases: [vpp, utk, v++]
    usage: Check out "/usl help" for command usage info